from constant import NYT_RELATION_LIST_STRING, NYT_EXAMPLE_5, NYT_STAR_RELATION_LIST_STRING, NYT_STAR_EXAMPLE_5, \
    WEBNLG_RELATION_LIST_STRING, WEBNLG_EXAMPLE_5, WEBNLG_STAR_RELATION_LIST_STRING, WEBNLG_STAR_EXAMPLE_5, \
    NYT_HRL_RELATION_LIST_STRING, NYT_HRL_EXAMPLE_5

DATA_PATH = './data'
DATASET_LIST = ['NYT', 'NYT-HRL', 'NYT-star', 'WebNLG', 'WebNLG-star']
DATASET_PROMPT_DICT = {
    'NYT': [NYT_RELATION_LIST_STRING, NYT_EXAMPLE_5],
    'NYT-star': [NYT_STAR_RELATION_LIST_STRING, NYT_STAR_EXAMPLE_5],
    'NYT-HRL': [NYT_HRL_RELATION_LIST_STRING, NYT_HRL_EXAMPLE_5],
    'WebNLG': [WEBNLG_RELATION_LIST_STRING, WEBNLG_EXAMPLE_5],
    'WebNLG-star': [WEBNLG_STAR_RELATION_LIST_STRING, WEBNLG_STAR_EXAMPLE_5]
}